version: '3'
services: 
  app-1.0:
    build: .
    ports:
      - 8000:8000
    volumes:
      - todo-frontend:/var/www/html
    networks:
      - frontend
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-container
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql
    networks:
      frontend:
    restart: always

volumes:
  todo-frontend:
  db:
# networks:
#   frontend:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.0.0.0/8

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: frontend
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.subnet: "192.168.1.0/24"

