pipeline{
    agent any

    environment {
        TAG = "${env.BRANCH_NAME}-${env.BUILD_NUMBER}"
        max = 20
        random_num = "${Math.abs(new Random().nextInt(max+1))}"
        PASSWORD = credentials('DOCKERHUB_PASSWORD')
    }

    stages{
        stage("Workspace initial Cleanup") {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Checkout Git') {
            steps {
                git branch: 'main', credentialsId: 'MayorFaj', url: 'https://github.com/MayorFaj/Migration-to-the-Cloud-with-Containerization.git'
            }
        }

        stage('Building application ') {
            steps {
                script {
                    
                    sh " docker login -u mayorfaj -p ${env.PASSWORD}"
                    sh " docker build -t mayorfaj/php-todo-app:${env.TAG} ."
                }
            }
        }

        stage('Creating docker container') {
            steps {
                script {
                    sh " docker run -d --name my-todo-app-${env.random_num} -p 8000:8000 mayorfaj/php-todo-app:${env.TAG}"
                }
            }
        }

        stage("Smoke Test") {
            steps {
                script {
                    sh "sleep 60"
                    sh "curl -I 54.167.99.240:8000"
                }
            }
        }

        stage("Publish to Registry") {
            steps {
                script {
                    sh " docker push mayorfaj/PHP-TODO-APP:1.0.0:${env.TAG}"
                }
            }
        }

        stage ('Clean Up') {
            steps {
                script {
                    sh " docker stop my-todo-app-${env.random_num}"
                    sh " docker rm my-todo-app-${env.random_num}"
                    sh " docker rmi mayorfaj/PHP-TODO-APP:1.0.0:${env.TAG}"
                }
            }
        }

        stage ('logout Docker') {
            steps {
                script {
                    sh " docker logout"
                }
            }
        }
    }
   
}